server:
  port: 8887

spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api-a:
      path: /lemon/**
      serviceId: service-napi
    auth:
      path: /auth/**
      serviceId: service-login-api
  add-host-header: true
  sensitive-headers:

token:
  secret: secret
  expiration: 1800
  header: X_Auth_Token
  refreshInterval: 3000
  cookieName: lemon_cookie
