server:
  port: 8887

spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-napi
