server:
  port: 8886

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: path_route
        uri: http://localhost:8888
        predicates:
          - Path=/lemon/**
        filters:
          - StripPrefix=1
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 10.101.228.79
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
      timeout: 1000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

token:
  secret: secret
  expiration: 1800
  header: X_Auth_Token
  refreshInterval: 300


